# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: dotnetRestoreAndBuild
  displayName: '.NET Restore and Build'
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  
  - script: dotnet restore
    displayName: 'Restore Dependencies'
    workingDirectory: 'TaskBlaster.TaskManagement'

  - script: dotnet build --no-restore --configuration Release
    displayName: 'Build'
    workingDirectory: 'TaskBlaster.TaskManagement'

- job: nextjsBuildAndLint
  displayName: 'Next.js Build and Lint'
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
  
  - script: npm install
    displayName: 'Install Dependencies'
    workingDirectory: 'taskblaster-web'

  - script: npm run lint
    displayName: 'Lint Code'
    workingDirectory: 'taskblaster-web'

  - script: npm run build
    displayName: 'Build Next.js App'
    workingDirectory: 'taskblaster-web'
